site_name: Protest Info
site_description: Info site for protecting your irl and online identity during a protest
site_author: Michael duPont
# site_url: localhost

repo_name: cforlando/protest-tips
repo_url: https://github.com/cforlando/protest-tips

theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true